---
title: The Risk Data Library
author: GFDRR
email: pchrzanowski@worldbank.org
description: ''
baseurl: dev.riskdatalibrary.org
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
